# Searching for dumbbells
dumbbellItemNumber: 14660327
dumbbellMentions: "<@U8UFH121F>"

# Searching for PS5 Physical Edition
ps5PhysicalItemNumber: "?"
ps5PhysicalMentions: "<@U8UFKNFQ9>"

# Searching for PS5 Digital Edition
ps5DigitalItemNumber: "?"
ps5DigitalMentions: "<@U8UFKNFQ9>"

# Interval at which to perform heartbeat check
interval: rate(1 minute)
