# Searching for dumbbells
dumbbellItemNumber: 14660327
# dumbbellMentions: "<@U8UFH121F>"
dumbbellMentions: "<@U8UFJ0GBT>"

# Searching for PS5 Physical Edition
ps5PhysicalItemNumber: 363472942
ps5PhysicalMentions: "<@U8UFJ0GBT>"

# Searching for PS5 Digital Edition
ps5DigitalItemNumber: 363472942
ps5DigitalMentions: "<@U8UFJ0GBT>"

# Interval at which to perform heartbeat check
interval: rate(1 minute)
