service: ammo-bot

custom: ${file(config.yml)}

provider:
  name: aws
  runtime: nodejs12.x
  # If you'd like to specify an existing IAM Role ARN for the lambda to execute as, put it here
  # role: insertIAMRoleARNHere

functions:
  search9mm:
    memorySize: 128
    handler: handler.heartbeat
    timeout: 60
    environment:
      serviceEndpoint: ${self:custom.serviceEndpoint}
      slackEndpoint: ${file(hooks.yml):slackEndpoint}
      httpMethod: ${self:custom.httpMethod}
      threshold: ${self:custom.threshold}
      searchString: ${self:custom.9mmSearchString}
      linkAndText: ${self:custom.9mmLinkAndText}
      mentions: ${self:custom.9mmMentions}
    events:
      - schedule: ${self:custom.interval}

  search40sw:
    memorySize: 128
    handler: handler.heartbeat
    timeout: 60
    environment:
      serviceEndpoint: ${self:custom.serviceEndpoint}
      slackEndpoint: ${file(hooks.yml):slackEndpoint}
      httpMethod: ${self:custom.httpMethod}
      threshold: ${self:custom.threshold}
      searchString: ${self:custom.40swSearchString}
      linkAndText: ${self:custom.40swLinkAndText}
      mentions: ${self:custom.40swMentions}
    events:
      - schedule: ${self:custom.interval}

  search45acp:
    memorySize: 128
    handler: handler.heartbeat
    timeout: 60
    environment:
      serviceEndpoint: ${self:custom.serviceEndpoint}
      slackEndpoint: ${file(hooks.yml):slackEndpoint}
      httpMethod: ${self:custom.httpMethod}
      threshold: ${self:custom.threshold}
      searchString: ${self:custom.45acpSearchString}
      linkAndText: ${self:custom.45acpLinkAndText}
      mentions: ${self:custom.45acpMentions}
    # events:
    #   - schedule: ${self:custom.interval}
